name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Prepare Environment
        run: |
          cp .env.example .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env
          sed -i 's/DB_DATABASE=lab-operation/DB_DATABASE=database\/database.sqlite/g' .env
          touch database/database.sqlite

      - name: Setup Application
        run: composer setup
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run CI Checks
        run: composer ci:check
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
